"""
Seed the hobbies collection with 60 diverse activities.
Run: python seed_hobbies.py
"""
from config import db

HOBBIES = [
    # ── OUTDOOR (10) ─────────────────────────────────────────
    {"name": "Trail Hiking", "category": "outdoor", "emoji": "🥾",
     "description": "Explore scenic trails and reconnect with nature on foot.",
     "tags": ["nature", "exercise", "adventure"], "indoor": False},
    {"name": "Rock Climbing", "category": "outdoor", "emoji": "🧗",
     "description": "Challenge gravity on natural rock faces or indoor walls.",
     "tags": ["adrenaline", "strength", "adventure"], "indoor": False},
    {"name": "Kayaking", "category": "outdoor", "emoji": "🛶",
     "description": "Paddle through calm lakes or rushing rivers.",
     "tags": ["water", "adventure", "nature"], "indoor": False},
    {"name": "Bird Watching", "category": "outdoor", "emoji": "🦅",
     "description": "Discover and identify local and migratory bird species.",
     "tags": ["nature", "patience", "learning"], "indoor": False},
    {"name": "Urban Gardening", "category": "outdoor", "emoji": "🌱",
     "description": "Grow herbs, flowers, or vegetables in your own space.",
     "tags": ["plants", "relaxing", "sustainable"], "indoor": False},
    {"name": "Stargazing", "category": "outdoor", "emoji": "🔭",
     "description": "Observe constellations, planets, and meteor showers.",
     "tags": ["night", "science", "peaceful"], "indoor": False},
    {"name": "Surfing", "category": "outdoor", "emoji": "🏄",
     "description": "Ride ocean waves and connect with the sea.",
     "tags": ["water", "adrenaline", "beach"], "indoor": False},
    {"name": "Camping", "category": "outdoor", "emoji": "⛺",
     "description": "Sleep under the stars and disconnect from the digital world.",
     "tags": ["nature", "adventure", "bonfire"], "indoor": False},
    {"name": "Mountain Biking", "category": "outdoor", "emoji": "🚵",
     "description": "Conquer trails on two wheels with adrenaline-pumping descents.",
     "tags": ["cycling", "adrenaline", "fitness"], "indoor": False},
    {"name": "Nature Photography", "category": "outdoor", "emoji": "📸",
     "description": "Capture the beauty of landscapes and wildlife through your lens.",
     "tags": ["photography", "nature", "creative"], "indoor": False},

    # ── CREATIVE (10) ────────────────────────────────────────
    {"name": "Watercolor Painting", "category": "creative", "emoji": "🎨",
     "description": "Create ethereal art with flowing water-based paints.",
     "tags": ["art", "relaxing", "expressive"], "indoor": True},
    {"name": "Pottery & Ceramics", "category": "creative", "emoji": "🏺",
     "description": "Shape clay into functional art on a potter's wheel.",
     "tags": ["tactile", "art", "meditative"], "indoor": True},
    {"name": "Street Photography", "category": "creative", "emoji": "📷",
     "description": "Document urban life and candid moments on the streets.",
     "tags": ["photography", "urban", "storytelling"], "indoor": False},
    {"name": "Creative Writing", "category": "creative", "emoji": "✍️",
     "description": "Craft stories, poetry, or personal essays from imagination.",
     "tags": ["writing", "storytelling", "expressive"], "indoor": True},
    {"name": "Hand Lettering", "category": "creative", "emoji": "🖊️",
     "description": "Master the art of beautiful, decorative handwritten typography.",
     "tags": ["design", "typography", "meditative"], "indoor": True},
    {"name": "Origami", "category": "creative", "emoji": "🦢",
     "description": "Transform flat paper into intricate three-dimensional sculptures.",
     "tags": ["paper", "patience", "precision"], "indoor": True},
    {"name": "Knitting & Crochet", "category": "creative", "emoji": "🧶",
     "description": "Create wearable art and cozy items with yarn and needles.",
     "tags": ["textile", "relaxing", "handmade"], "indoor": True},
    {"name": "Woodworking", "category": "creative", "emoji": "🪵",
     "description": "Build furniture and objects from raw lumber with your hands.",
     "tags": ["building", "tools", "tactile"], "indoor": True},
    {"name": "Digital Illustration", "category": "creative", "emoji": "🖌️",
     "description": "Create stunning art on a tablet with infinite possibilities.",
     "tags": ["digital", "art", "design"], "indoor": True},
    {"name": "Songwriting", "category": "creative", "emoji": "🎵",
     "description": "Compose melodies and lyrics that tell your story.",
     "tags": ["music", "expressive", "creative"], "indoor": True},

    # ── SOCIAL (10) ──────────────────────────────────────────
    {"name": "Board Game Nights", "category": "social", "emoji": "🎲",
     "description": "Gather friends for strategy, laughs, and friendly rivalry.",
     "tags": ["friends", "strategy", "fun"], "indoor": True},
    {"name": "Book Club", "category": "social", "emoji": "📚",
     "description": "Read and discuss thought-provoking books with others.",
     "tags": ["reading", "discussion", "learning"], "indoor": True},
    {"name": "Cooking Class", "category": "social", "emoji": "👨‍🍳",
     "description": "Learn new cuisines and techniques alongside fellow foodies.",
     "tags": ["food", "learning", "social"], "indoor": True},
    {"name": "Improv Comedy", "category": "social", "emoji": "🎭",
     "description": "Think on your feet and create spontaneous comedy gold.",
     "tags": ["comedy", "confidence", "creativity"], "indoor": True},
    {"name": "Community Volunteering", "category": "social", "emoji": "🤝",
     "description": "Give back to your local community through meaningful service.",
     "tags": ["giving", "community", "purpose"], "indoor": False},
    {"name": "Language Exchange", "category": "social", "emoji": "🗣️",
     "description": "Learn a new language by teaching yours to someone else.",
     "tags": ["language", "culture", "learning"], "indoor": True},
    {"name": "Pub Trivia", "category": "social", "emoji": "🧠",
     "description": "Test your knowledge in a fun, competitive team setting.",
     "tags": ["trivia", "competition", "fun"], "indoor": True},
    {"name": "Salsa Dancing", "category": "social", "emoji": "💃",
     "description": "Learn partner dances and meet amazing new people.",
     "tags": ["dance", "fitness", "social"], "indoor": True},
    {"name": "Wine & Cheese Tasting", "category": "social", "emoji": "🍷",
     "description": "Explore flavour pairings and refine your palate with friends.",
     "tags": ["food", "tasting", "sophisticated"], "indoor": True},
    {"name": "Open Mic Night", "category": "social", "emoji": "🎤",
     "description": "Share your talent on stage or cheer on brave performers.",
     "tags": ["music", "performance", "community"], "indoor": True},

    # ── SOLO (10) ────────────────────────────────────────────
    {"name": "Meditation & Mindfulness", "category": "solo", "emoji": "🧘",
     "description": "Find inner peace through guided or silent practice.",
     "tags": ["mindfulness", "health", "peaceful"], "indoor": True},
    {"name": "Journaling", "category": "solo", "emoji": "📓",
     "description": "Document your thoughts, goals, and daily reflections.",
     "tags": ["writing", "reflection", "mindfulness"], "indoor": True},
    {"name": "Jigsaw Puzzles", "category": "solo", "emoji": "🧩",
     "description": "Piece together beautiful images one satisfying piece at a time.",
     "tags": ["puzzle", "patience", "relaxing"], "indoor": True},
    {"name": "Artisan Baking", "category": "solo", "emoji": "🍞",
     "description": "Master sourdough, pastries, and bread from scratch.",
     "tags": ["baking", "food", "patience"], "indoor": True},
    {"name": "Deep Reading", "category": "solo", "emoji": "📖",
     "description": "Dive into novels, non-fiction, or philosophy for hours.",
     "tags": ["reading", "learning", "peaceful"], "indoor": True},
    {"name": "Candle Making", "category": "solo", "emoji": "🕯️",
     "description": "Craft custom scented candles for yourself or as gifts.",
     "tags": ["craft", "scents", "relaxing"], "indoor": True},
    {"name": "Model Building", "category": "solo", "emoji": "🛩️",
     "description": "Assemble detailed miniatures, dioramas, and scale models.",
     "tags": ["precision", "patience", "building"], "indoor": True},
    {"name": "Coin Collecting", "category": "solo", "emoji": "🪙",
     "description": "Curate a collection of historical coins and treasures.",
     "tags": ["collecting", "history", "treasure"], "indoor": True},
    {"name": "Learning an Instrument", "category": "solo", "emoji": "🎸",
     "description": "Pick up guitar, piano, ukulele, or any instrument you love.",
     "tags": ["music", "practice", "creative"], "indoor": True},
    {"name": "Solo Travel Planning", "category": "solo", "emoji": "🗺️",
     "description": "Research and plan your next adventure to somewhere new.",
     "tags": ["travel", "planning", "adventure"], "indoor": True},

    # ── PHYSICAL (10) ────────────────────────────────────────
    {"name": "Yoga Flow", "category": "physical", "emoji": "🧘‍♀️",
     "description": "Build flexibility, strength, and mind-body connection.",
     "tags": ["fitness", "flexibility", "mindfulness"], "indoor": True},
    {"name": "Boxing & Kickboxing", "category": "physical", "emoji": "🥊",
     "description": "Build confidence and fitness with powerful striking techniques.",
     "tags": ["combat", "fitness", "confidence"], "indoor": True},
    {"name": "Lap Swimming", "category": "physical", "emoji": "🏊",
     "description": "Glide through water for a full-body, low-impact workout.",
     "tags": ["water", "fitness", "endurance"], "indoor": True},
    {"name": "Martial Arts", "category": "physical", "emoji": "🥋",
     "description": "Learn discipline and self-defense through traditional forms.",
     "tags": ["discipline", "combat", "fitness"], "indoor": True},
    {"name": "Bouldering", "category": "physical", "emoji": "🧱",
     "description": "Solve physical puzzles on climbing walls without ropes.",
     "tags": ["climbing", "problem-solving", "strength"], "indoor": True},
    {"name": "Parkour", "category": "physical", "emoji": "🤸",
     "description": "Move through urban environments with fluid, creative movement.",
     "tags": ["urban", "adrenaline", "agility"], "indoor": False},
    {"name": "Fencing", "category": "physical", "emoji": "🤺",
     "description": "Master the art of sword fighting with speed and strategy.",
     "tags": ["combat", "strategy", "elegance"], "indoor": True},
    {"name": "Archery", "category": "physical", "emoji": "🏹",
     "description": "Find focus and precision with bow and arrow.",
     "tags": ["precision", "focus", "outdoor"], "indoor": False},
    {"name": "Skateboarding", "category": "physical", "emoji": "🛹",
     "description": "Learn tricks and cruise through the city on four wheels.",
     "tags": ["urban", "tricks", "creative"], "indoor": False},
    {"name": "Dance Fitness", "category": "physical", "emoji": "🕺",
     "description": "Get fit with choreographed routines to upbeat music.",
     "tags": ["dance", "fitness", "fun"], "indoor": True},

    # ── DIGITAL (10) ─────────────────────────────────────────
    {"name": "Coding Side Projects", "category": "digital", "emoji": "💻",
     "description": "Build apps, tools, or websites just for the fun of it.",
     "tags": ["programming", "building", "learning"], "indoor": True},
    {"name": "Game Development", "category": "digital", "emoji": "🎮",
     "description": "Create your own video games from concept to playable build.",
     "tags": ["gaming", "creative", "programming"], "indoor": True},
    {"name": "3D Modeling & Printing", "category": "digital", "emoji": "🖨️",
     "description": "Design digital objects and bring them to life with a 3D printer.",
     "tags": ["3d", "design", "making"], "indoor": True},
    {"name": "Video Editing", "category": "digital", "emoji": "🎬",
     "description": "Tell cinematic stories through professional video production.",
     "tags": ["video", "storytelling", "creative"], "indoor": True},
    {"name": "Podcasting", "category": "digital", "emoji": "🎙️",
     "description": "Share your voice, ideas, and stories with the world.",
     "tags": ["audio", "storytelling", "community"], "indoor": True},
    {"name": "Blogging", "category": "digital", "emoji": "✏️",
     "description": "Build an audience through written content and personal stories.",
     "tags": ["writing", "community", "creative"], "indoor": True},
    {"name": "UI/UX Design", "category": "digital", "emoji": "🎯",
     "description": "Design beautiful, intuitive digital experiences that delight users.",
     "tags": ["design", "creative", "tech"], "indoor": True},
    {"name": "Music Production", "category": "digital", "emoji": "🎹",
     "description": "Produce beats and tracks in a digital audio workstation.",
     "tags": ["music", "creative", "tech"], "indoor": True},
    {"name": "VR Exploration", "category": "digital", "emoji": "🥽",
     "description": "Dive into virtual worlds, games, and immersive experiences.",
     "tags": ["vr", "gaming", "tech"], "indoor": True},
    {"name": "Drone Photography", "category": "digital", "emoji": "🚁",
     "description": "Capture stunning aerial perspectives with a camera drone.",
     "tags": ["photography", "tech", "aerial"], "indoor": False},
]


def seed():
    db.hobbies.drop()
    result = db.hobbies.insert_many(HOBBIES)
    print(f"✅ Seeded {len(result.inserted_ids)} hobbies into the database!")

    # Print category breakdown
    from collections import Counter
    cats = Counter(h["category"] for h in HOBBIES)
    for cat, count in sorted(cats.items()):
        print(f"   {cat}: {count}")


if __name__ == "__main__":
    seed()
